version: '3.4'
services:
    swarm.dnp.dappnode.eth:
        image: 'swarm.dnp.dappnode.eth:0.1.0'
        build: ./build
        volumes:
            - 'swarm:/root/.ethereum'
        environment:
            - PASSWORD=edu
            - PORT=30399
            - BZZPORT=8500
volumes:
    swarm: {}
