version: '3.4'
services:
  swarm.dnp.dappnode.eth:
    image: 'swarm.dnp.dappnode.eth:0.3.2'
    build: ./build
    ports:
      - '30399:30399'
      - '30399:30399/udp'
    volumes:
      - 'swarm:/root/.ethereum'
    environment:
      - ACCOUNT
      - PASSWORD
      - ENS
      - BZZPORT=80
      - EXTRA_OPTS=--enable-pinning
    restart: always
volumes:
  swarm: {}
