version: '3.4'
services:
  swarm.dnp.dappnode.eth:
    image: 'swarm.dnp.dappnode.eth:0.2.2'
    build: ./build
    ports:
      - '8500:8500'
    volumes:
      - 'swarm:/root/.ethereum'
    environment:
      - PASSWORD=
      - PORT=30399
      - BZZPORT=8500
    dns: 172.33.1
volumes:
  swarm: {}
